main:
  - name: 简介
    url: /
    weight: 10
  - name: 科研
    url: /#research
    weight: 11
  - name: 当前研究
    url: /#current-work
    weight: 12
  - name: 论文
    url: /#papers
    weight: 13
  - name: 荣誉
    url: /#awards
    weight: 14
